### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by herangli** [M-Dehghanimadvar/PV_Manufacturing_Supply_Chain#1]
Dear M-Dehghanimadvar,

I tried to run your supply chain optimization project in python but I am facing an error.  
1. I installed all required python library which you wrote in Readme file. I used last released version of libraries.
2. I renamed xlsx file to Data.xlsx
3. I called `python.exe .\Financial_Analysis.py`

Could you help me to solve this error? 

The error message is the following:
```
python.exe .\Financial_Analysis.py
User time: 0.33463025093078613 s
# ==========================================================
# = Solver Results                                         =
# ==========================================================
# ----------------------------------------------------------
#   Problem Information
# ----------------------------------------------------------
Problem:
- Lower bound: -inf
  Upper bound: inf
  Number of objectives: 1
  Number of constraints: 388
  Number of variables: 6271
  Number of nonzeros: 11827
  Sense: unknown
# ----------------------------------------------------------
#   Solver Information
# ----------------------------------------------------------
Solver:
- Status: ok
  User time: 0.0
  Termination condition: unknown
  Error rc: 0
  Time: 0.15871667861938477
ERROR: evaluating object as numeric value: module_center[Newcastle]
        (object: <class 'pyomo.core.base.var._GeneralVarData'>)
    No value for uninitialized NumericValue object module_center[Newcastle]
ERROR: evaluating object as numeric value:
    46389026.823319495*module_center[Newcastle] +
    46389026.823319495*module_center[Blacktown] +
    46389026.823319495*module_center[Central Coast] +
    46389026.823319495*module_center[Parramatta] +
    46389026.823319495*module_center[Shoalhaven] +
    46389026.823319495*module_center[Wyndham] +
    46389026.823319495*module_center[Hume] +
    46389026.823319495*module_center[Brimbank] +
    46389026.823319495*module_center[Moreland] +
    46389026.823319495*module_center[Casey] +
    46389026.823319495*module_center[DarwinP] +
    46389026.823319495*module_center[Palmerston] +
    46389026.823319495*module_center[Litchfield] +
    46389026.823319495*module_center[Katherine] +
    46389026.823319495*module_center[East Arnhem] +
    46389026.823319495*module_center[Gold Coast] +
    46389026.823319495*module_center[Moreton Bay] +
    46389026.823319495*module_center[Logan] +
    46389026.823319495*module_center[Ipswich] +
    46389026.823319495*module_center[Bundaberg] +
    46389026.823319495*module_center[Wanneroo] +
    46389026.823319495*module_center[Swan] +
    46389026.823319495*module_center[Rockingham] +
    46389026.823319495*module_center[Gosnells] +
    46389026.823319495*module_center[Mandurah] +
    46389026.823319495*module_center[Onkaparinga] +
    46389026.823319495*module_center[Salisbury] +
    46389026.823319495*module_center[Playford] +
    46389026.823319495*module_center[Marion] +
    46389026.823319495*module_center[Campbelltown]
        (object: <class 'pyomo.core.expr.numeric_expr.SumExpression'>)
    No value for uninitialized NumericValue object module_center[Newcastle]
Traceback (most recent call last):
  File ".\Financial_Analysis.py", line 1, in <module>
    from Results import *
  File "C:\Users\Herangli\PycharmProjects\attila_analysis\Results.py", line 7, in <module>
    CapEx = value(sum(model.module_center[potential_manufacturer] *
  File "pyomo\core\expr\numvalue.pyx", line 157, in pyomo.core.expr.numvalue.value
  File "pyomo\core\expr\numvalue.pyx", line 142, in pyomo.core.expr.numvalue.value
  File "pyomo\core\expr\numeric_expr.pyx", line 210, in pyomo.core.expr.numeric_expr.ExpressionBase.__call__
```

Used libraries:
1. Pyomo              6.4.1
2. pandas             1.4.3
3. numpy              1.22.3
4. numpy-financial    1.0.0

Thank you for your help in advance

**Comment by M-Dehghanimadvar** [comment]
There was an issue with capacity parameters, which is fixed now!

**Comment by herangli** [comment]
Thank you very much. 

I ckecked it and it seems to work well. 

I am using a free version of IBM CPLEX and  I hit the ,,complexity maximum" so the optimization engine isn't run because limitations.  Now I try to use gplk optimization enginge to check.  I have read that it is more slower that cplex but it is also able to find the optimum just we have to wait for it. Do you have experience whit this glpk solver? Is glpk worth a try or do we have to buy IBM Cplex?

**Comment by M-Dehghanimadvar** [comment]
Sorry for the late reply. I am not sure what you meant by limitation. CPLEX has a student version, did you try that?
GLPK may not be the best option if you have a big MILP problem. GURABI is another solver that provides free versions for students. You may find that faster for running your problem. Also, there is a good tutorial on using Pyomo published by NREL. I believe it would be really helpful.
